# Generated by Django 4.0 on 2021-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_alter_blog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='temp.Tags'),
        ),
    ]
